name: Deploy and Run .NET App Without Systemd

on:
  push:
    branches:
      - master  # Adjust this based on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 62.240.120.106 >> ~/.ssh/known_hosts

    - name: Publish .NET Application
      run: |
        dotnet publish -c Release -o ./publish

    - name: Copy Published Files to Server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 62.240.120.106  # Server IP Address
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./publish/*
        target: /home/${{ secrets.SSH_USERNAME }}/app/publish
        port: 22

    - name: Run .NET Application on Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@62.240.120.106 << 'EOF'
          cd /home/${{ secrets.SSH_USERNAME }}/app/publish
          fuser -k 5000/tcp || true  # Kill any existing app running on port 5000
          nohup dotnet TestAPI.dll --urls "http://10.1.7.37:5001" > output.log 2>&1 &
        EOF