name: Deploy and Run .NET App Without Systemd

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your-server-hostname.com >> ~/.ssh/known_hosts

    - name: Publish .NET Application
      run: |
        dotnet publish -c Release -o ./publish

    - name: Copy Published Files to Server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./publish/*
        target: /home/${{ secrets.SSH_USERNAME }}/app/publish
        port: 22

    - name: Run .NET Application on Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USERNAME }}/app/publish
          # Kill any existing app instances running on port 5000 (optional)
          fuser -k 5001/tcp || true
          
          # Run the application on a specific URL
          nohup dotnet TestAPI.dll --urls "http://10.1.7.37:5001" > output.log 2>&1 &
        EOF
